name: C/C++ CI default macos-latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get compiler version
      run: g++ -v
    - name: Create output folder
      run: mkdir Build
    - name: make
      run: make
